### ISSUE TITLE
mobilenet_publisher Acquisition of distance coordinates

### ISSUE THREAD

**Issue by yo4hi6o** [luxonis/depthai-ros-examples#41]
Hi
Thank you for the wonderful repository. mobilenet_publisher
Will the acquisition of the distance coordinates of be implemented in the future?

```
roslaunch depthai_examples mobile_publisher.launch 
rostopic echo /mobilenet_publisher/color/mobilenet_detections
```

```
        id: 11
        score: 0.7041015625
        pose: 
          pose: 
            position: 
              x: 0.0
              y: 0.0
              z: 0.0
            orientation: 
              x: 0.0
              y: 0.0
              z: 0.0
              w: 0.0
          covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    bbox: 
      center: 
        x: 38.0
        y: 137.0
        theta: 0.0
      size_x: 76.0
      size_y: 262.0
    source_img: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: ''
      height: 0
      width: 0
      encoding: ''
      is_bigendian: 0
      step: 0
      data: []
---
```
